server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
    disruptionBudget:
      enabled: true
      maxUnavailable: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
