{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

{{- template "openbao.csiEnabled" . -}}
{{- if .csiEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openbao.fullname" . }}-csi-provider
  namespace: {{ include "openbao.namespace" . }}
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    {{- if  .Values.csi.serviceAccount.extraLabels -}}
      {{- toYaml .Values.csi.serviceAccount.extraLabels | nindent 4 -}}
    {{- end -}}
  {{ template "csi.serviceAccount.annotations" . }}
{{- end }}
