{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

{{ template "openbao.mode" . }}
{{- if ne .mode "external" }}
{{- if ne .mode "dev" }}
{{- if .serverEnabled -}}
{{- if eq (include "openbao.tls.useGeneratedIssuer" .) "true" -}}
# Self-signed cert-manager Issuer for the OpenBao server TLS certificate.
# Generated because global.tlsDisable=false, server.tls.source=certManager,
# server.tls.certManager.generateIssuer=true and no clusterIssuerName is set.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "openbao.fullname" . }}-issuer
  namespace: {{ include "openbao.namespace" . }}
  labels:
    helm.sh/chart: {{ include "openbao.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    app.kubernetes.io/component: server
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  selfSigned: {}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
