{{- if and .Values.snapshotAgent.enabled .Values.snapshotAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openbao.snapshotAgent.serviceAccount.name" . }}
  namespace: {{ include "openbao.namespace" . }}
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    {{- if  .Values.snapshotAgent.serviceAccount.extraLabels -}}
      {{- toYaml .Values.snapshotAgent.serviceAccount.extraLabels | nindent 4 -}}
    {{- end -}}
  {{ template "openbao.snapshotAgent.serviceAccount.annotations" . }}
{{ end }}
